-- Eliminar la tabla si existe para asegurar un inicio limpio
DROP TABLE IF EXISTS product;

-- Crear la tabla PRODUCT
CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    price NUMERIC(10, 2) NOT NULL,
    stock INT
);

